### ISSUE TITLE
Design data access layer that Controllers can interact with

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-WebService#45]
Start work on the implemenation of the data access layer. Implement at least the deserializing of result sets from database (From string to object). 

Take a look at [chapter 3](http://ce.sharif.edu/courses/97-98/2/ce418-1/resources/root/Books/Patterns%20of%20Enterprise%20Application%20Architecture%20-%20Martin%20Fowler.pdf) for inspiration on patterns

Dependent on:
p7-team/p7-report#30
#47 

Tasks: 
- [x] Connect with and extract information from the database
- [x] Determine and implement appropriate pattern (possibly Repository Pattern)

**Comment by soenderby** [comment]
A little explaination:

# Data Access Layer documentation/explaination

The data access, that is communication with the database, should be handled by repositories.
There should be one repository for each [aggregate root](https://martinfowler.com/bliki/DDD_Aggregate.html). In our context an aggregate root is a class in our domain model,
that is the models/classes we operate on in the domain logic.
If a model contains data that is spread across multiple tables in the database, the use should never have to be concerned
with fetching data from the tables. This is the responsibility of the repository for that model.
However in order to reduce the responsibilities placed on a single repository, it may be prudent to create repositories for
the constituent data. However these repositories should not be exposed to the domain logic, instead they should only be
consumed by repositories for aggregate models.

A repository is created by implementing the **IRepository\<T, K\>** interface
The generic type **T** should be the type of the model/object that should have CRUD operations. This class must implement the
**IAggregateRoot\<K\>** interface, which is explained below.
The type **K** should be the type that used to identify an item in the database, or a class from which this data can be derived.

The **IAggregate\<K\>** Interface should be implemented by models that have a repository. This interface defines the **GetIdentifier**
method. This method should return an object that is used to identify an instance of the model in the database.
The purpose of this interface is to allow specific implementations to define how they are identified.
For the **User** class the identifier is simply the primary key in the database, the **Id** property. Thus it implements the interface
**IAggregate\<int\>** and a call to **\<userInstance\>.GetIdentifier()** will return the id as an integer.

However it is possible to define a model and repository for an aggregate with data divided over several tables in the database.
Because the data is spread out, it would not be possible to define a single value that would be able to identify all the data needed, without placing many restrictions on the structure of the data.

**Comment by soenderby** [comment]
You can use [SqlKata](https://sqlkata.com/) or [Dapper](https://dapper-tutorial.net/) to construct queries.
I have added a QueryFactory as a parameter to UserRepository, which is the connection object used with SqlKata.
For dapper you should add IDBConnectionFactory as a parameter.

Repositories should be added to the DI container in program.cs, such that they are automatically passed to controllers.
I have already done this for UserRepository, so it should be a simple case of replicating it.
